export default defineEventHandler((event) => {

    return [
        {
            id: 1,
            name: "Apple Headphone",
            image: "/allproducts/headphone.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
            discount: "-40%",
        },
        {
            id: 2,
            name: "Rayban Sunglasses",
            image: "/allproducts/sunglasses.png",
            price: "960",
            prevPrice: "1160",
            rating: 5,
            ratingCount: 30,
            discount: "-35%",
        },
        {
            id: 3,
            name: "Samsung S20",
            image: "/allproducts/smart01.webp",
            price: "160",
            prevPrice: "170",
            rating: 4,
            ratingCount: 50,
            discount: "-40%",
        },
        {
            id: 4,
            name: "Galaxy S21 5G",
            image: "/allproducts/smart02.webp",
            price: "360",
            prevPrice: "460",
            rating: 5,
            ratingCount: 100,
            discount: "-40%",
        },
        {
            id: 5,
            name: "Samsung A15",
            image: "/allproducts/smart03.webp",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 6,
            name: "Smart Watch",
            image: "/allproducts/smartwatch.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 7,
            name: "Louder Speaker",
            image: "/allproducts/speaker.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 8,
            name: "The Speaker",
            image: "/allproducts/smallspeaker.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 9,
            name: "Old Radio",
            image: "/allproducts/radio.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 10,
            name: "Medical Kit",
            image: "/allproducts/kit.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 11,
            name: "Samsung S1",
            image: "/allproducts/laptop.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 12,
            name: "Microphone X",
            image: "/allproducts/micro.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 13,
            name: "DSLR Camera",
            image: "/allproducts/dslr.webp",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 14,
            name: "Old Car",
            image: "/allproducts/car.webp",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 15,
            name: "Tom Toy",
            image: "/allproducts/tom.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 16,
            name: "Jerry Toy",
            image: "/allproducts/jerry.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 17,
            name: "Watch Gold",
            image: "/allproducts/gwatch.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 18,
            name: "Men's T-Shirt",
            image: "/allproducts/tshirt.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 19,
            name: "Hoodie Jacket",
            image: "/allproducts/hodie.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 20,
            name: "Assasin's Dress",
            image: "/allproducts/assasin.webp",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 21,
            name: "Men's belt",
            image: "/allproducts/belt.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
            discount: "-40%",
            brand: "Apple",
            color: "Red",
            categories: ["Clothing"],
        },
        {
            id: 22,
            name: "AI Shoe",
            image: "/allproducts/aishoe.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
            brand: "Nike",
            color: "Red",
            categories: ["Menshoes"],
        },
    ];
});