export default defineEventHandler((event) => {

    return [
        {
            id: 1,
            name: "The north coat",
            image: "/images/pro-1.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
            discount: "-40%",
        },
        {
            id: 2,
            name: "Gucci duffle bag",
            image: "/images/bag.png",
            price: "960",
            prevPrice: "1160",
            rating: 5,
            ratingCount: 30,
            discount: "-35%",
        },
        {
            id: 3,
            name: "RGB liquid CPU Cooler",
            image: "/images/pro-3.png",
            price: "160",
            prevPrice: "170",
            rating: 4,
            ratingCount: 50,
            discount: "-40%",
        },
        {
            id: 4,
            name: "Small BookSelf",
            image: "/images/pro-4.png",
            price: "360",
            prevPrice: "460",
            rating: 5,
            ratingCount: 100,
            discount: "-40%",
        },
        {
            id: 5,
            name: "The Eos Camera",
            image: "/images/camera.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 6,
            name: "The Teddy",
            image: "/images/teddy.jpg",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 7,
            name: "The Jacket",
            image: "/images/jacket.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 8,
            name: "The Car",
            image: "/images/car.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 9,
            name: "The Gamepad",
            image: "/images/gamepad.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 10,
            name: "The Laptop",
            image: "/images/laptop.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 11,
            name: "The Shoe",
            image: "/images/shoe.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 12,
            name: "The Watch",
            image: "/images/shoe.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 13,
            name: "The Watch",
            image: "/images/shoe.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 14,
            name: "The Watch",
            image: "/images/shoe.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 15,
            name: "The Watch",
            image: "/images/shoe.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 16,
            name: "The Watch",
            image: "/images/shoe.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 17,
            name: "The Watch",
            image: "/images/shoe.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 18,
            name: "The Watch",
            image: "/images/shoe.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 19,
            name: "The Watch",
            image: "/images/shoe.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 20,
            name: "The Watch",
            image: "/images/shoe.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 21,
            name: "The Watch",
            image: "/images/shoe.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
        {
            id: 22,
            name: "The Watch",
            image: "/images/shoe.png",
            price: "260",
            prevPrice: "360",
            rating: 4,
            ratingCount: 65,
        },
    ];
});